### ISSUE TITLE
Http Proxy

### ISSUE THREAD

**Issue by PatrickHollweck** [elastic/app-search-php#50]
Currently, as far as I have seen there is no way to set an HTTP proxy. If there already is a way we should document that!

I would be open to adding this functionality, but we should discuss how the API should look.
Any Ideas? I think a `setProxy` and `getProxy` method on the `ClientBuilder` should work

**Comment by JasonStoltz** [comment]
Hi @PatrickHollweck. We will be deprecating this client soon in favor of https://github.com/elastic/enterprise-search-php. I recommend taking a look at that.
